curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-allergyintolerance.xml > us-core-allergyintolerance.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-careteam.xml > us-core-careteam.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-condition.xml > us-core-condition.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-device.xml > us-core-device.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-diagnosticreport.xml > us-core-diagnosticreport.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-goal.xml > us-core-goal.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-immunization.xml > us-core-immunization.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-location.xml > us-core-location.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-medication.xml > us-core-medication.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-medicationrequest.xml > us-core-medicationrequest.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-medicationstatement.xml > us-core-medicationstatement.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-practitioner.xml > us-core-practitioner.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-procedure.xml > us-core-procedure.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-observationresults.xml > us-core-observationresults.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-smokingstatus.xml > us-core-smokingstatus.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-careplan.xml > us-core-careplan.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-organization.xml > us-core-organization.profile.xml
curl http://hl7.org/fhir/us/core/StructureDefinition-us-core-patient.xml > us-core-patient.profile.xml

curl https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-race.xml > us-core-race.extension.xml
curl https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-ethnicity.xml > us-core-ethnicity.extension.xml
curl https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-birthsex.xml > us-core-birthsex.extension.xml
